language: android
android:
  components:
    - build-tools-19.0.3
    - extra-google-m2repository
    - extra-android-m2repository
    - android-16
    - sysimg-16
  licences:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#selendroid"
    on_success: always
    on_failure: always
    use_notice: true
  
branches:
  only:
    - master

before_install: 
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "mvn --version"
  - "cd third-party/"
  - "./mvnInstall.sh"
  - "cd ../"

script: 
  - "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml"


env:
  global:
    - secure: "qOCTIN+N9lYVx/rp7Qu5xcyaFPLsf64UYSOY5dq+4jOx5vokQfb0vwFxKyDJcUD7ow3GMhw11280HE2OZ3Xk+1xRGWND5Axhey8BPOjqT9D+vjKY2o2Q2ZmUbBTapL/lDixjnV9Gk/bJLytPLNaaA7S/HNfp0g03bWhLanz5fgg="
    - secure: "BzwsXUidLx7X733KzZDwvuXsIiFD0WazDABk8FM3BuvkJnGd8xp84A0ZwZ76PYvrxWp/MncyaOytkrnNA86rnBmpWvcnWzEuBVoDY/cEc4q1SnLjgsRByanNBPoYopFHAVRI2zvkU8hSBVFZC2+ABi3vpNhgYr0LtBhZouBTX5E="
