language: java

notifications:
  email: false

before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools  
  - android update sdk --filter platform-tools,android-16,android-10,sysimg-16  --no-ui --force
  - echo no | android create avd -n emulator16Uk -t android-16 --skin WVGA800 --abi x86 --force

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - emulator -avd emulator16Uk -prop persist.sys.language=en -prop persist.sys.country=UK -noaudio -no-boot-anim &
  - sleep 5 # give the emulator some time to start, otherwise the script will fail
  - ./wait_for_emulator.sh 

script:
  - mvn install
  - adb kill-server
  - adb start-server
  - adb devices
  - adb install -r selendroid-server/target/selendroid-server-0.3.apk
  - adb install -r selendroid-test-app/target/selendroid-test-app-0.3.apk
  - ./selendroid-server/start-server.sh 
  - cd selendroid-large-tests
  - mvn install -DskipTests=false
